added example and notest of handling toast activation using in memory…
MicrosoftDocs/winrt-api pull request #1753
Opened 2020-07-31 16:16 UTC by nicuparente

… event handlers

2020-07-31 16:16 UTC, PRMerger9 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-07-31 16:48 UTC, PRMerger18 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-07-31 18:59 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +> It is recommended for Windows Applications,such as UWP or MSIX packaged applications, to use [OnActivated](..\windows.ui.xaml\application_onactivated_603737819.md) for handling activation.
What about Sparse Signed Packaged apps? They will have to implement a background trigger I believe since there is no windows.ui.xaml OnActivated event for thos.

2020-07-31 19:00 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +> It is recommended for Windows Applications,such as UWP or MSIX packaged applications, to use [OnActivated](..\windows.ui.xaml\application_onactivated_603737819.md) for handling activation.
What about SSP? There is no OnActivated event for those win32 apps since they may not be xaml based. They will have to implement a Push Trigger right?

2020-07-31 19:01 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +            notification.Activated += ToastNotificationCallback_Activated;
The same applies to other event handlers like Dismissed and Expired. Do you want to add that too?

2020-07-31 19:02 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +        }
There should be a cleanup function too which removes the event handler for the toasts. Most likely in the destructor of this class

2020-07-31 19:03 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +class ...{
In general, I think we want to ensure that this code compiles. Have you verified that?

2020-07-31 19:11 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +- Starting WinRT 19041, MSIX packaged desktop applications should use the [OnActivated](\\windows.ui.xaml\application_onactivated_603737819.md) for handling toast activations rather than subscribing
OnActivated in the Xaml namespace won't work for SSP. They have to implement Push Triggers. I would suggest a link specifically to the SSP documentation to implement Push triggers with CLSID

2020-08-01 01:44 UTC, PRMerger17 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-01 01:47 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +            notification.Activated += ToastNotificationCallback_Activated;
I added a note on the description of the example that the following pattern can be followed on the dismissed and expired events.

2020-08-01 01:48 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +        }
Added a clean up function to remove the toast notification from the list and do a garbarge collection.

2020-08-01 01:49 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +class ...{
Updated with class name. Verified that the code compiles

2020-08-01 01:49 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +- Starting WinRT 19041, MSIX packaged desktop applications should use the [OnActivated](\\windows.ui.xaml\application_onactivated_603737819.md) for handling toast activations rather than subscribing
I removed this based on andrews previous comment on other PR.

2020-08-04 00:19 UTC, kyungal approved these changes

2020-08-04 00:41 UTC, hulumane approved these changes

2020-08-04 15:12 UTC, PRMerger8 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-04 16:22 UTC, ktoliver commented
@kyungal @hulumane Thank you for your reviews. In the public repository, a member of the content team or a PM must sign off on a pull request before it's ready to merge.

@hickeys Could you take a look? Thanks.

2020-08-04 17:05 UTC, hickeys commented on windows.ui.notifications/toastnotification.md
> +    {
The code is indented one level more than the class declaration. Please de-indent code one level.

2020-08-04 17:05 UTC, hickeys commented on windows.ui.notifications/toastnotification.md
> +The following example shows how to add an event handler for toast activation on running desktop apps. ToastNotifications need to be persisted in a list to maintain a reference to the toast for later
Needs a period at the end of the sentence that begins with "A similar pattern..."

2020-08-04 17:07 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +- A desktop app must subscribe to at least the [Activated](toastnotification_activated.md) event to handle activation.
I feel that we should mention this: Apps should be using BG activations or Nitro if possible over Activation events if available.

There should also be:
1) Pointer to the nitro page for OS clients that need bg activations.
2) For sparse signed packages (Ala Carte), there should be a link to how Desktop apps can subscribe to BG activations (Please sync up with Arup Roy for this)

2020-08-04 17:08 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +            GC.Collect();
Don't need GC.Collect. Lets skip it please

2020-08-04 17:09 UTC, hickeys commented on windows.ui.notifications/toastnotification.md
> +        }
I'm a little confused about the call to GC.Collect(). Is that required for all toast notifications that have been persisted this way? Wouldn't removing the notification from the list and removing the event handler be enough to have this be automatically collected when the garbage collector ran next? What's the reason for forcing the GC to run during destruction?

2020-08-04 17:09 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +
There needs to be a destructor in the class which iterates through the toast list and unsubscribes the event handlers. Otherwise, we expose the leaked ref in the platform.

2020-08-04 17:09 UTC, hickeys requested changes
Three comments. Two are the most trivial of nitpicks, and the other is more of a question to help me understand what's going on.

2020-08-04 20:36 UTC, PRMerger15 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-04 20:40 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +    {
Removed indentation

2020-08-04 20:40 UTC, nicuparente commented on windows.ui.notifications/toastnotification.md
> +
Added a class destructor.

2020-08-04 21:18 UTC, hulumane approved these changes

2020-08-04 21:19 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +        }
Optional: Clear the list after removing the event handlers

2020-08-04 21:20 UTC, hulumane approved these changes

2020-08-04 22:02 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +- A desktop app must subscribe to at least the [Activated](toastnotification_activated.md) event to handle activation.
Not sure why this is the first point when we are trying to dissuade devs from using event handlers. It's only a last option. We should always favor background events over this approach.

2020-08-04 22:02 UTC, PRMerger6 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-04 22:04 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +The following example shows how to add an event handler for toast activation on running desktop apps. ToastNotifications need to be persisted in a list to maintain a reference to the toast for later
You should also mention that not unsubscribing from event handlers could leak references in the platform. So it is good practise to persist in a list and unsubscribe the events on destruction.

2020-08-04 22:19 UTC, PRMerger10 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-04 22:21 UTC, hulumane commented on windows.ui.notifications/toastnotification.md
> +    - If none of the options does not fit your application, follow the example in this document for properly using event handlers.
Double negative in this statement :)

2020-08-04 22:36 UTC, PRMerger15 commented
@nicuparente : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-08-04 22:36 UTC, hulumane approved these changes

2020-08-04 23:26 UTC, hickeys approved these changes

2020-08-04 23:26 UTC, merged